### PR TITLE
Use Symfony error and exception handling

### LINKED ISSUE #16: Replace TYPO3 error/exception handling with symfony one

### PR DESCRIPTION
**Pull request by Aricura**
| Q | A
| --- | ---
| Fixed tickets | fixes #16 
| Related issues/PRs | 
| License | GPL-3.0+
| Documentation License | CC BY-SA 4.0

#### What's in this PR?

The PR uses the Symfony Debug Error and Exception handling instead of the TYPO3 one.

It also includes a fix for the TwigBundle and BartacusTwigBundle which prevent the rendering of Fatal Errors because their output buffers won't be closed by default.

### CODE REVIEW

**Comment by EmiiKhaos** [comment]
Can you fix the code style issue and add an entry to the changelog? (please amend the commit)

File: Config/ConfigLoader.php [hunk 1]
```diff
@@ -47,9 +49,17 @@ public function loadFromAdditionalConfiguration(): void
     {
         $this->contentElement->load();
 
-        // remove TYPO3 error and exception handler to use Symfony instead
-        $GLOBALS['TYPO3_CONF_VARS']['SYS']['productionExceptionHandler'] = '';
-        $GLOBALS['TYPO3_CONF_VARS']['SYS']['debugExceptionHandler'] = '';
+        if ($_SERVER['APP_DEBUG']) {
```
Comment (EmiiKhaos) [inline Config/ConfigLoader.php]: Please inject the `kernel.debug` parameter and us this one

File: Config/ConfigLoader.php [hunk 2]
```diff
@@ -47,9 +49,17 @@ public function loadFromAdditionalConfiguration(): void
...
+            // remove TYPO3 error and exception handler to use Symfony instead, if in DEBUG mode
+            $GLOBALS['TYPO3_CONF_VARS']['SYS']['debugExceptionHandler'] = '';
+            $GLOBALS['TYPO3_CONF_VARS']['SYS']['productionExceptionHandler'] = '';
+        } else {
+            // use custom TYPO3 exception handler if not in DEBUG mode to fix the Output Buffer issue of
+            // the TwigBundle and BartacusTwigBundle
+            $GLOBALS['TYPO3_CONF_VARS']['SYS']['debugExceptionHandler'] = Typo3DebugExceptionHandler::class;
+            $GLOBALS['TYPO3_CONF_VARS']['SYS']['productionExceptionHandler'] = Typo3ProductionExceptionHandler::class;
+        }
+
```
Comment (EmiiKhaos) [inline Config/ConfigLoader.php]: Can you please extract this block into it's own config loader class? I never made interfaces nor kernel tags for that, but that would be quite nice

File: Config/ConfigLoader.php [hunk 3]
```diff
@@ -47,9 +49,17 @@ public function loadFromAdditionalConfiguration(): void
...
         $GLOBALS['TYPO3_CONF_VARS']['SYS']['errorHandler'] = '';
```
Comment (EmiiKhaos) [inline Config/ConfigLoader.php]: Setting `errorHandler` to nothing is correct in all cases?

**Comment by EmiiKhaos** [comment]
Should this qualify as feature or bugfix?
